routes/web.php
<?php

use App\Http\Controllers\PartThreeController;
use App\Http\Controllers\PartTwoController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');
Route::group(['prefix' => 'part-2'], function (): void {
    Route::get('/nomor-3', [PartTwoController::class, 'numberThreePage'])->name('nomor-3-page');
    Route::post('/nomor-3', [PartTwoController::class, 'numberThreeProcess'])->name('nomor-3-process');

    Route::get('/nomor-4', [PartTwoController::class, 'numberFourPage'])->name('nomor-4-page');
    Route::post('/nomor-4', [PartTwoController::class, 'numberFourProcess'])->name('nomor-4-process');

    Route::get('/nomor-5', [PartTwoController::class, 'numberFivePage'])->name('nomor-5-page');
    Route::post('/nomor-5', [PartTwoController::class, 'numberFiveProcess'])->name('nomor-5-process');
});
Route::group(['prefix' => 'part-three'], function (): void {
    Route::get('/', function () {
        return view('part-three.dashboard');
    })->name('index-dashboard');
    Route::get('/get-product', [PartThreeController::class, 'getProduct'])->name('get-product');
    Route::get('/get-detail-product', [PartThreeController::class, 'getDetailProduct'])->name('get-detail-product');
    Route::delete('/delete', [PartThreeController::class, 'deleteProduct'])->name('delete-product');
    Route::post('/save-product', [PartThreeController::class, 'saveProduct'])->name('save-product');

    Route::get('/transaction', function () {
        return view('part-three.transaction');
    })->name('index-transaction');

});

Route::resource('transaction', TransactionController::class);
Route::get('/transaction/data/get', [TransactionController::class, 'getData'])->name('transaction.getData');
Route::put('/transaction/editproduct/{id}', [TransactionController::class, 'editProduct'])->name('transaction.editProduct');
Route::delete('/transaction/deleteproduct/{id}', [TransactionController::class, 'deleteProduct'])->name('transaction.deleteProduct');

app/Http/Controllers/PartThreeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Http\Request;
use App\Models\User;
use DataTables;
use Illuminate\Routing\Controller as BaseController;
use Yajra\DataTables\DataTables as DataTablesDataTables;
use Yajra\DataTables\Facades\DataTables as FacadesDataTables;

class PartThreeController extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;

    public function getProduct(Request $request)  {
        if ($request->ajax()) {
            $data = Product::select('*')->orderBy('id', 'desc');
            return DataTablesDataTables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
       
                        $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editProduct">Edit</a>';
   
                        $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteProduct">Delete</a>';
      
                            return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
          
        return view('users');

    }
    public function saveProduct(Request $request) {
        Product::updateOrCreate([
            'id' => $request->product_id
        ],
        [
            'name' => $request->name, 
            'code' => $request->code,
            'price' => $request->price,
        ]);        

        return response()->json(['success'=>'Product saved successfully.']);
        // return view('part-two.number-three');
    }

    public function getDetailProduct(Request $request){
        $product = Product::find($request->id);
        return response()->json($product);
    }

    public function deleteProduct(Request $request)
    {
        Product::find($request->id)->delete();
      
        return response()->json(['success'=>'Product deleted successfully.']);
    }

    public function addTransactionPage(){
        $products = Product::get();
        return view('part-three.transaction-form', ['products' => $products]);
    }
}

resources/views/part-three/dashboard.blade.php
@extends('part-three.layout')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap5.min.css" rel="stylesheet">
@endSection
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="row">    
        <!-- Area Chart -->
        <div class="col-xl-12 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                    </div>
                </div>
                
                <!-- Card Body -->
                <div class="card-body">
                    <a class="btn btn-success" href="javascript:void(0)" id="createNewProduct"> Create New Product</a>
                    <div class="">
                        <table class="table table-bordered data-table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Code</th>
                                    <th>Price</th>
                                    <th width="100px">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->
</div>
@endsection
@section('modal')
<div class="modal fade" id="ajaxModel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="productForm" name="productForm" class="form-horizontal">
                   <input type="hidden" name="product_id" id="product_id">
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="code" class="col-sm-2 control-label">Code</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="code" name="code" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="price" class="col-sm-2 control-label">price</label>
                        <div class="col-sm-12">
                            <input type="number" class="form-control" id="price" name="price" placeholder="Price" value="" maxlength="50" required="">
                        </div>
                    </div>
       
                    <div class="col-sm-offset-2 col-sm-10">
                     <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
                     </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap5.min.js"></script>
<script>
    $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('get-product') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'code', name: 'code'},
            {data: 'price', name: 'price', render: (data, type, row) => rupiah(data), searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });

    $('#createNewProduct').click(function () {
        $('#saveBtn').val("create-product");
        $('#product_id').val('');
        $('#productForm').trigger("reset");
        $('#modelHeading').html("Create New Product");
        $('#ajaxModel').modal('show');
    });

    $('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Sending..');
      
        $.ajax({
          data: $('#productForm').serialize(),
          url: "{{ route('save-product') }}",
          type: "POST",
          dataType: 'json',
          success: function (data) {
              $('#productForm').trigger("reset");
              $('#ajaxModel').modal('hide');
              sweet_alert("success", "Berhasil", "Success").then(function (e) {
                    // window.location.href = res.data.url;
                    table.draw();
                }, function (dismiss) {
                    return false;
                })
           
          },
          error: function (data) {
              console.log('Error:', data);
              $('#saveBtn').html('Save Changes');
          }
      });
    });

    $('body').on('click', '.editProduct', function () {
      var product_id = $(this).data('id');
      $.get("{{ route('get-detail-product') }}" +'?id=' + product_id , function (data) {
        console.log(data);
          $('#modelHeading').html("Edit Product");
          $('#saveBtn').val("edit-user");
          $('#ajaxModel').modal('show');
          $('#product_id').val(data.id);
          $('#name').val(data.name);
          $('#code').val(data.code);
          $('#price').val(data.price);
      })
    });
    $('body').on('click', '.deleteProduct', function () {
     
     var product_id = $(this).data("id");
     confirm("Are You sure want to delete !");
     
     $.ajax({
         type: "DELETE",
         url: "{{ route('delete-product') }}"+'?id='+product_id,
         success: function (data) {
            sweet_alert("success", "Berhasil", "Success").then(function (e) {
                    // window.location.href = res.data.url;
                    table.draw();
                }, function (dismiss) {
                    return false;
                })
         },
         error: function (data) {
             console.log('Error:', data);
         }
     });
 });
</script>
@endsection

resources/views/part-three/show.blade.php
@extends('part-three.layout')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 mb-1">
            <h2>Transaction Detail</h2>
        </div>
        <div class="col-md-6 text-end mb-1">
            <h5> {{ $transaction->transaction_number }}</h5>
        </div>
    </div>

    <div class="card bg-white px-5 pt-3 mb-3">
        <div class="card-body">
            <div class="my-3">
                <div class="row">
                    <div class="col-md-6 col-md-6 mb-3">
                        <h6>Customer Name</h6>
                        <h5 class="fw-bold">{{ $transaction->customer_name }}</h5>
                    </div>
                    <div class="col-md-6 col-md-6 mb-3">
                        <h6>Date</h6>
                        <h5 class="fw-bold">{{ \Carbon\Carbon::parse($transaction->date)->format('Y F d') }}</h5>
                    </div>
                    <div class="col-md-6 col-md-6 mb-3">
                        <h6>Total Price</h6>
                        <h5 class="fw-bold">{{ number_format($transaction->total_price,2,',','.'); }}</h5>
                    </div>
                    <div class="col-md-6 col-md-6 mb-3">
                        <h6>Total Quantity</h6>
                        <h5 class="fw-bold">{{ number_format($transaction->total_quantity,2,',','.') }}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card bg-white px-5 py-4">
        <div class="card-body">
            <h4 class="card-title">Products</h4>
            <table class="table" id="products-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($transaction->details as $detail)
                        <tr>
                            <td>{{ $detail->product->name }}</td>
                            <td>{{ number_format($detail->quantity,2,',','.') }}</td>
                            <td>{{ number_format($detail->total_price,2,',','.') }}</td>
                            <td>
                                <button type="button" class="btn btn-warning btn-sm edit-product" data-id="{{ $detail->id }}" data-quantity="{{ $detail->quantity }}"><i class="fas fa-pencil"></i></button>
                                <button type="button" class="btn btn-danger btn-sm delete-product" data-id="{{ $detail->id }}"><i class="fas fa-trash"></i></button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('modal')
    <!-- Modal Edit Product -->
    <div class="modal fade" id="editProductModal" tabindex="-1" aria-labelledby="editProductModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editProductModalLabel">Edit Product</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="editProductForm">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="productId" id="editProductId">
                        <div class="mb-3">
                            <label for="editQuantity" class="form-label">Quantity</label>
                            <input type="number" class="form-control" id="editQuantity" name="quantity" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Delete Product -->
    <div class="modal fade" id="deleteProductModal" tabindex="-1" aria-labelledby="deleteProductModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteProductModalLabel">Delete Product</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="deleteProductForm">
                        @csrf
                        @method('DELETE')
                        <input type="hidden" name="deleteProductId" id="deleteProductId">
                        <p>Are you sure you want to delete this product?</p>
                        <button type="submit" class="btn btn-danger">Delete Product</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script>
        $(document).ready(function () {
            $('#products-table').on('click', '.edit-product', function () {
                const productId = $(this).data('id');
                const quantity = $(this).data('quantity');

                $('#editProductModal #editProductId').val(productId);
                $('#editProductModal #editQuantity').val(quantity);
                $('#editProductModal').modal('show');
            });

            $('#products-table').on('click', '.delete-product', function () {
                const productId = $(this).data('id');
                $('#deleteProductModal #deleteProductId').val(productId);
                $('#deleteProductModal').modal('show');
            });

            $('#editProductForm').submit(function (e) {
                e.preventDefault();
                const productId = $('#editProductId').val();
                const quantity = $('#editQuantity').val();
                $.ajax({
                    url: '/transaction/editproduct/' + productId,
                    method: 'PUT',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    data: { 
                        quantity: quantity, 
                    },
                    success: function (response) {
                        console.log(response);
                        $('#editProductModal').modal('hide');
                        location.reload();
                    },
                    error: function (error) {
                        console.error(error);
                    }
                });
            });

            $('#deleteProductForm').submit(function (e) {
                e.preventDefault();
                const productId = $('#deleteProductId').val();
                $.ajax({
                    url: '/transaction/deleteproduct/' + productId,
                    method: 'DELETE',
                    data: {
                        "_token": "{{ csrf_token() }}",
                    },
                    success: function (response) {
                        $('#deleteProductModal').modal('hide');
                        location.reload();
                    },
                    error: function (error) {
                        console.error(error);
                    }
                });
            });
        });

    </script>
@endSection 

resources/views/part-three/transaction-form.blade.php
@extends('part-three.layout')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="col-lg-12">

    <!-- Custom Text Color Utilities -->
        <form action="{{ route('transaction.store') }}" method="post" id="transaction-form">
            @csrf
            <div class="card bg-white px-5 pt-3 mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div class="form-group">
                                <label for="customer_name">Customer Name</label>
                                <input type="text" name="customer_name" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div class="form-group mb-3">
                                <label for="date">Date</label>
                                <input type="date" name="date" class="form-control" required>
                            </div>
                        </div>
                    </div>   
                </div>
            </div>

            <div class="card bg-white px-5 py-4">
                <div class="card-body">
                    <h3 class="card-title">Product</h3>
                        <table class="table table-responsive" id="products-table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Quantity</th>
                                    <th>Total Price</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="product-row">
                                    <td>
                                        <select name="products[][product_id]" class="form-control product-select" required>
                                            <option value="">Select Product</option>
                                            @foreach ($products as $product)
                                                <option value="{{ $product->id }}" data-price="{{ $product->price }}">{{ $product->name }}</option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <input type="number" name="products[][quantity]" class="form-control product-quantity" required>
                                    </td>
                                    <td>
                                        <input type="text" name="products[][total_price]" class="form-control product-total-price" readonly>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-success add-product">Add Product</button>
                                    </td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="2"></td>
                                    <td>Total: <span id="total-amount">0</span></td>
                                    <td></td>
                                </tr>
                            </tfoot>
                        </table>
                    <div class="form-group">
                        
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>

</div>
@endsection
@section('js')
<script>
    $(document).ready(function () {
            $('#products-table').on('click', '.add-product', function () {
                const productRow = $(this).closest('tr').clone();
                productRow.find('.product-select, .product-quantity, .product-total-price').val('');
                $('#products-table tbody').append(productRow);
                // remove btn add produk != last
                $('#products-table tbody .add-product').not(':last').prop('disabled', true).remove();
            });
    
            $('#products-table tbody').on('input', '.product-quantity', function () {
                const row = $(this).closest('tr');
                const quantity = $(this).val();
                const productPrice = row.find('.product-select option:selected').data('price');
    
                if (quantity && productPrice) {
                    const totalPrice = quantity * productPrice;
                    row.find('.product-total-price').val(totalPrice.toFixed(2));
                } else {
                    row.find('.product-total-price').val('');
                }
    
                updateTotalAmount();
            });
    
            function updateTotalAmount() {
                let totalAmount = 0;
                $('#products-table tbody .product-total-price').each(function () {
                    const value = parseFloat($(this).val());
                    if (!isNaN(value)) {
                        totalAmount += value;
                    }
                });
                $('#total-amount').text(totalAmount.toFixed(2));
            }
    
            $('#transaction-form').submit(function () {
                $('#products-table tbody .add-product').prop('disabled', false);
    
                const productsData = [];
                $('#products-table tbody tr').each(function () {
                    const productId = $(this).find('.product-select').val();
                    const quantity = $(this).find('.product-quantity').val();
                    const totalPrice = $(this).find('.product-total-price').val();
    
                    if (productId && quantity && totalPrice) {
                        productsData.push({
                            product_id: productId,
                            quantity: quantity,
                            total_price: totalPrice,
                        });
                    }
                });
    
                $('<input>').attr({
                    type: 'hidden',
                    name: 'products_data',
                    value: JSON.stringify(productsData),
                }).appendTo('#transaction-form');
    
                return true;
            });
        });
    </script>
</script>
@endsection

resources/views/part-three/transaction.blade.php
@extends('part-three.layout')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap5.min.css" rel="stylesheet">
@endSection
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="row">    
        <!-- Area Chart -->
        <div class="col-xl-12 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                    </div>
                </div>
                
                <!-- Card Body -->
                <div class="card-body">
                    <a class="btn btn-success" href="{{route('transaction.create')}}" id="createNewProduct">Create Transaksi</a>
                    <div class="">
                        <table class="table pt-2" id="transactions-table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Customer Name</th>
                                    <th>Trx Number</th>
                                    <th>Date</th>
                                    <th>Total Quanitity</th>
                                    <th>Total Price</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->
</div>
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap5.min.js"></script>
<script>
    $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    $('#transactions-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('transaction.getData') }}",
        columns: [
            { data: 'id', name: 'id' },
            { data: 'customer_name', name: 'customer_name' },
            { data: 'transaction_number', name: 'transaction_number' },
            { data: 'date', name: 'date' },
            { data: 'total_quantity', name: 'total_quantity', render: (data, type, row) => numberWithCommas(data) },
            { data: 'total_price', name: 'total_price', render: (data, type, row) => rupiah(data) },
            { data: 'action', name: 'action', orderable: false, searchable: false },
        ],
    });
</script>
@endsection